CREATE TABLE movies (
  id serial not null,
  title varchar(255) NOT NULL,
  year varchar(5) NOT NULL,
  genre int(11) NOT NULL,
  duration varchar(20) default NULL
);


INSERT INTO movies (id, duration,genre,title,year) VALUES ('1', '154 мин','1','А был ли Каротин','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('2', '133 мин','2','А в России опять окаянные дни','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('3', '90 мин','1','А вдруг это любовь?','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('4', '96 мин','2','А вот и моя крошка','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('5', '90 мин','1','А вот и Полли','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('6', '84 мин','1','А вы любили когда-нибудь?','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('7', '102 мин','3','А если это любовь?','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('8', '188 мин','2','А зори здесь тихие...','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('9', '23 мин','2','А к нам цирк приехал','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('10', '97 мин','1','А как же Боб?','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('11', '88 мин','4','А кто-то все видит','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('12', '106 мин','1','А мне так нравится','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('13', '31 мин','2','А потом оглянулся...','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('14', '90 мин','1','А поутру они проснулись...','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('15', '118 мин','2','А причем здесь любовь','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('16', '','5','А прошлое кажется сном','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('17', '88 мин','1','А спать с чужой женой хорошо?','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('18', '88 мин','1','А теперь кое-что совсем другое','1971');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('19', '110 мин','6','А теперь не смотри','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('20', '133 мин','3','А теперь, дамы и господа...','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('21', '116 мин','2','А у вас который час?','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('22', '88 мин','2','А у нас была тишина','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('23', '65 мин','7','А человек играет на трубе','1970');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('24', '71 мин','1','А чой-то ты во фраке?','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('25', '127 мин','2','А это случилось в Виши','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('26', '41 мин','1','А. Чехов. Сценки','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('27', '139 мин','2','Абай','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('28', '95 мин','7','Абба: фильм','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('29', '89 мин','1','Абдулладжан, или Посвящается Стивену Спилбергу','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('30', '80 мин','2','Абитуриентка','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('31', '132 мин','2','Абориген','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('32', '87 мин','8','Абраксас, хранитель вселенной','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('33', '80 мин','9','Абрафакс под пиратским флагом','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('34', '85 мин','2','Абрек Заур','1926');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('35', '88 мин','8','Абсолютная агрессия','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('36', '122 мин','4','Абсолютная власть','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('37', '97 мин','8','Абсолютная реальность','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('38', '93 мин','8','Абсолютная сила','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('39', '88 мин','1','Абсурдистан','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('40', '151 мин','10','Абу Райхан Беруни','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('41', '97 мин','2','Абулхаир-Хан','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('42', '106 мин','8','Авалон','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('43', '126 мин','1','Авалон','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('44', '95 мин','8','Авалон: подводная миссия','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('45', '114 мин','3','Авансцена','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('46', '144 мин','1','Аванти!','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('47', '81 мин','1','Авантюра','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('48', '104 мин','11','Авантюристы','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('49', '139 мин','4','Авария','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('50', '98 мин','4','Авария','1965');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('51', '87 мин','4','Авария','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('52', '93 мин','4','Авария','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('53', '99 мин','2','Авария - дочь мента','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('54', '','11','Аватар','2009');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('55', '92 мин','2','Август','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('56', '75 мин','2','Август','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('57', '113 мин','2','Август Раш','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('58', '94 мин','2','Августовская рапсодия','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('59', '87 мин','2','Августовские киты','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('60', '84 мин','2','Авдотья Павловна','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('61', '96 мин','2','Аве Мария','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('62', '97 мин','1','Аве Цезарь','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('63', '100 мин','2','Аветик','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('64', '170 мин','2','Авиатор','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('65', '101 мин','11','Авиатор','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('66', '92 мин','10','Авиценна','1956');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('67', '','12','','');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('68', '149 мин','12','Авраам','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('69', '112 мин','2','Аврора','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('70', '90 мин','11','Аврора: операция перехват','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('71', '','13','Австралия','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('72', '89 мин','2','Австрийское поле','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('73', '94 мин','1','Автобусная остановка','1956');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('74', '100 мин','4','Автокатастрофа','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('75', '86 мин','11','Автоматик','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('76', '76 мин','1','Автомобиль на крыше','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('77', '101 мин','1','Автомобиль, скрипка и собака Клякса','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('78', '97 мин','1','Автомойка','1976');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('79', '4600 мин','13','Автономка','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('80', '67 мин','5','Автопортрет в гробу, в кандалах и с саксофоном','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('81', '74 мин','2','Автопортрет неизвестного','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('82', '94 мин','7','Автор песен','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('83', '110 мин','1','Автора! Автора!','1982');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('84', '100 мин','11','Авторитет','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('85', '56 мин','1','Автостоп','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('86', '110 мин','13','Автостопом по Галактике','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('87', '86 мин','1','Автостоянка','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('88', '81 мин','14','Автоэротика. Дневники Красной Туфельки 4','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('89', '78 мин','4','Агапэ','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('90', '104 мин','4','Агата','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('91', '90 мин','11','Агент','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('92', '80 мин','1','Агент &quot;Дикая утка','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('93', '99 мин','13','Агент 117','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('94', '64 мин','1','Агент в мини-юбке','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('95', '93 мин','1','Агент Джонни Инглиш','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('96', '110 мин','11','Агент Коди Бэнкс','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('97', '100 мин','11','Агент Коди Бэнкс 2: Пункт назначения - Лондон','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('98', '97 мин','11','Агент на льду','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('99', '624 мин','11','Агент национальной безопасности 1','1998');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('100', '624 мин','11','Агент национальной безопасности 2','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('101', '624 мин','11','Агент национальной безопасности 3','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('102', '600 мин','11','Агент национальной безопасности 4','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('103', '600 мин','11','Агент национальной безопасности 5','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('104', '85 мин','8','Агент по имени Дилайла','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('105', '95 мин','1','Агент поневоле','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('106', '86 мин','4','Агент секретной службы','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('107', '415 мин','1','Агентство','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('108', '1248 мин','4','Агентство &quot;Золотая пуля','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('109', '717 мин','1','Агентство 2','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('110', '832 мин','1','Агентство НЛС','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('111', '640 мин','1','Агентство НЛС 2','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('112', '104 мин','2','Агенты','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('113', '88 мин','1','Агенты КГБ тоже влюбляются','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('114', '88 мин','1','Агенты ФБР','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('115', '94 мин','11','Агирре, гнев божий','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('116', '122 мин','1','Агитбригада &quot;Бей врага!','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('117', '97 мин','6','Агнесса божья','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('118', '143 мин','2','Агония','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('119', '134 мин','2','Агония и экстаз','1965');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('120', '98 мин','2','Ад','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('121', '98 мин','2','Ад','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('122', '102 мин','11','Ад в открытом море','1954');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('123', '165 мин','11','Ад в поднебесье','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('124', '102 мин','11','Ад в Тихом океане','1968');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('125', '90 мин','15','Ад для героев','1962');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('126', '98 мин','6','Ад живых мертвецов','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('127', '91 мин','6','Ад каннибалов','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('128', '144 мин','2','Ад, или Досье на самого себя','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('129', '109 мин','1','Ада','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('130', '131 мин','7','Адам женится на Еве','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('131', '99 мин','1','Адам и Ева','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('132', '71 мин','1','Адам и Хева','1969');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('133', '86 мин','2','Адам хочет быть человеком','1959');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('134', '94 мин','1','Адамовы яблоки','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('135', '114 мин','1','Адаптация','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('136', '205 мин','2','Адвокат','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('137', '1404 мин','4','Адвокат','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('138', '138 мин','2','Адвокат дьявола','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('139', '96 мин','2','Адвокат как доверенное лицо','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('140', '85 мин','1','Адвокат на каникулы','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('141', '135 мин','5','Адвокат террора','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('142', '103 мин','2','Административная власть','1954');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('143', '93 мин','2','Адмирал Нахимов','1946');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('144', '107 мин','2','Адмирал Ушаков','1953');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('145', '','2','Адмиралъ','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('146', '104 мин','10','Адольф Гитлер. Билет в одну сторону','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('147', '72 мин','8','Адреналин','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('148', '87 мин','11','Адреналин','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('149', '','11','Адреналин 2','2009');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('150', '86 мин','2','Адрес вашего дома','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('151', '88 мин','4','Адрес неизвестен','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('152', '117 мин','2','Адрес неизвестен','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('153', '83 мин','6','Адская женушка','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('154', '95 мин','4','Адская кухня','1998');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('155', '86 мин','6','Адская месть','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('156', '88 мин','6','Адская месть II: Кровавые крылья','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('157', '','11','Адская поездка','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('158', '83 мин','6','Адская тварь','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('159', '96 мин','11','Адские охотники','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('160', '90 мин','11','Адский бункер','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('161', '89 мин','2','Адский вылет','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('162', '89 мин','1','Адский небоскреб','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('163', '92 мин','1','Адское такси','1998');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('164', '394 мин','13','Адъютант его превосходительства','1969');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('165', '4420 мин','3','Адъютанты любви','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('166', '156 мин','2','Аз воздам','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('167', '208 мин','4','Азазель','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('168', '124 мин','1','Азартная игра','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('169', '108 мин','2','Азартная игра','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('170', '720 мин','2','Азбука любви','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('171', '96 мин','16','Азбука футбола','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('172', '81 мин','11','Азиат','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('173', '90 мин','11','Азиат','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('174', '90 мин','16','Азирис Нуна','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('175', '99 мин','9','Азур и Азмар','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('176', '98 мин','2','Ай лав ю, Петрович!','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('177', '102 мин','2','Ай, Кармела!','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('178', '99 мин','1','Айболит-66','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('179', '106 мин','12','Айвенго','1952');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('180', '149 мин','12','Айвенго','1982');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('181', '300 мин','12','Айвенго','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('182', '99 мин','2','Айдахо для меня одного','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('183', '72 мин','2','Айна','1930');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('184', '72 мин','2','Айналайын','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('185', '78 мин','3','Айрик','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('186', '90 мин','2','Айрис','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('187', '140 мин','2','Айседора','1968');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('188', '100 мин','3','Айя','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('189', '100 мин','4','Академик из Аскании','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('190', '90 мин','1','Академия ведьм','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('191', '88 мин','1','Академия порока 5','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('192', '89 мин','1','Академия Рашмор','1998');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('193', '110 мин','2','Академия смерти','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('194', '103 мин','1','Аквамарин','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('195', '124 мин','11','Акира','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('196', '120 мин','2','Аккаттоне!','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('197', '111 мин','2','Аккомпаниаторша','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('198', '102 мин','8','Аккумулятор','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('199', '','1','Акселератка','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('200', '96 мин','2','Акт мести','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('201', '99 мин','2','Актеры','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('202', '75 мин','3','Актриса','1943');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('203', '89 мин','2','Актриса','1953');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('204', '87 мин','11','Акула','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('205', '90 мин','6','Акула-монстр','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('206', '68 мин','5','Акулы','1982');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('207', '92 мин','11','Акулы','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('208', '89 мин','11','Акулы 2','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('209', '42 мин','5','Акулы 3D','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('210', '88 мин','5','Акулы! В дикой природе: пираты глубин','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('211', '51 мин','5','Акулы: машина смерти','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('212', '91 мин','13','Акция','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('213', '101 мин','11','Акция смерти','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('214', '90 мин','16','Аладдин','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('215', '','16','Аладдин: арабские приключения Аладдина','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('216', '42 мин','16','Аладдин: арабские приключения. Джин в бутылке','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('217', '42 мин','16','Аладдин: арабские приключения. Тайные сокровища','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('218', '84 мин','1','Аладдин-99','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('219', '110 мин','2','Аламбриста!','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('220', '161 мин','15','Аламо','1960');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('221', '170 мин','12','Аламо: тринадцать дней к славе','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('222', '134 мин','2','Алая буква','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('223', '86 мин','2','Алая буква','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('224', '110 мин','1','Алекс в стране чудес','1970');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('225', '96 мин','1','Алекс и Эмма','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('226', '175 мин','11','Александр','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('227', '140 мин','12','Александр Великий','1956');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('228', '111 мин','2','Александр Невский','1938');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('229', '90 мин','15','Александр Пархоменко','1942');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('230', '104 мин','7','Александр Рэгтайм Бэнд','1938');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('231', '','2','Александр. Невская битва','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('232', '90 мин','2','Александра','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('233', '89 мин','1','Аленка','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('234', '40 мин','16','Аленький цветочек','1952');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('235', '66 мин','16','Аленький цветочек','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('236', '72 мин','9','Алеша Попович и Тугарин Змей','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('237', '88 мин','3','Алешкина любовь','1960');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('238', '95 мин','11','Алжир','1938');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('239', '85 мин','2','Али','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('240', '156 мин','11','Али','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('241', '87 мин','11','Али-баба и сорок разбойников','1944');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('242', '73 мин','16','Али-баба и сорок разбойников','1983');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('243', '28 мин','16','Али-баба и сорок разбойников','1959');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('244', '90 мин','1','Алиби','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('245', '110 мин','2','Алиса в городах','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('246', '134 мин','16','Алиса в стране чудес','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('247', '74 мин','16','Алиса в стране чудес','1951');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('248', '','13','Алиса в стране чудес','2010');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('249', '113 мин','2','Алиса здесь больше не живет','1975');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('250', '76 мин','4','Алиса и букинист','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('251', '66 мин','7','Алла Пугачева: &quot;Не делайте мне больно, господа','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('252', '98 мин','11','Аллан Куотермейн и потерянный Город Золота','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('253', '94 мин','6','Аллигатор','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('254', '85 мин','6','Аллигатор-гигант','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('255', '89 мин','11','Алмаз смерти','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('256', '260 мин','13','Алмазная тропа','1978');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('257', '76 мин','4','Алмазы для Марии','1975');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('258', '112 мин','4','Алмазы шаха','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('259', '143 мин','2','Алое и черное','1983');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('260', '89 мин','6','Алтарь зла','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('261', '88 мин','3','Алые паруса','1961');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('262', '69 мин','15','Алый знак доблести','1951');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('263', '89 мин','12','Алый наряд','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('264', '98 мин','4','Алый рассвет','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('265', '93 мин','2','Альбино аллигатор','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('266', '200 мин','2','Алькатрас: вся шокирующая история','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('267', '122 мин','4','Альфа Дог','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('268', '99 мин','2','Альфавиль','1964');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('269', '74 мин','1','Альфонс','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('270', '104 мин','1','Альфредо, Альфредо','1971');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('271', '99 мин','1','Алюминиевые человечки','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('272', '96 мин','11','Аляска','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('273', '102 мин','1','Аляска, сэр!','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('274', '157 мин','2','Амадей','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('275', '85 мин','8','Амазония','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('276', '91 мин','11','Амазонка в огне','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('277', '81 мин','11','Амазонки золотого храма','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('278', '94 мин','12','Амазонки и гладиаторы','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('279', '85 мин','1','Амазонки на Луне','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('280', '87 мин','3','Аманда','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('281', '93 мин','8','Аманда и инопланетянин','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('282', '126 мин','1','Амаркорд','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('283', '130 мин','11','Амбер навсегда','1947');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('284', '120 мин','1','Амели','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('285', '95 мин','11','Амелия Эрхарт: последний полет','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('286', '112 мин','2','Америка','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('287', '174 мин','2','Америка, Америка','1963');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('288', '86 мин','11','Американец','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('289', '113 мин','7','Американец в Париже','1951');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('290', '90 мин','3','Американка','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('291', '90 мин','6','Американская готика','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('292', '88 мин','1','Американская девственница','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('293', '98 мин','3','Американская дочь','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('294', '119 мин','4','Американская история Икс','1998');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('295', '99 мин','2','Американская мечта','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('296', '98 мин','5','Американская мечта','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('297', '102 мин','4','Американская мечта','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('298', '107 мин','1','Американская мечта','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('299', '120 мин','2','Американская ночь','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('300', '102 мин','3','Американская рапсодия','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('301', '101 мин','11','Американская рулетка','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('302', '768 мин','2','Американская трагедия','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('303', '99 мин','1','Американская школа','1983');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('304', '94 мин','11','Американские бродяги','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('305', '93 мин','11','Американские герои','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('306', '114 мин','4','Американские горки','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('307', '110 мин','1','Американские граффити','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('308', '','11','Американские драконы','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('309', '88 мин','11','Американские Коммандос','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('310', '112 мин','2','Американские молнии','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('311', '90 мин','2','Американские часы','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('312', '87 мин','2','Американский бизон','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('313', '89 мин','6','Американский вампир','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('314', '99 мин','2','Американский гимн','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('315', '84 мин','2','Американский гражданин','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('316', '72 мин','1','Американский дедушка','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('317', '88 мин','11','Американский дракон','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('318', '127 мин','4','Американский друг','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('319', '117 мин','3','Американский Жиголо','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('320', '95 мин','11','Американский киборг Стальной Воин','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('321', '88 мин','11','Американский кикбоксер','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('322', '95 мин','11','Американский ниндзя','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('323', '96 мин','11','Американский ниндзя II - конфронтация','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('324', '90 мин','11','Американский ниндзя III - кровавая охота','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('325', '96 мин','11','Американский ниндзя IV: полное уничтожение','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('326', '97 мин','11','Американский ниндзя V','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('327', '97 мин','6','Американский оборотень в Лондоне','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('328', '95 мин','6','Американский оборотень в Париже','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('329', '92 мин','1','Американский пирог','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('330', '105 мин','1','Американский пирог 2','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('331', '97 мин','1','Американский пирог: Свадьба','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('332', '85 мин','11','Американский полицейский','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('333', '107 мин','3','Американский президент','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('334', '97 мин','6','Американский психопат','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('335', '85 мин','6','Американский психопат 2: стопроцентная американка','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('336', '94 мин','11','Американский самурай','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('337', '81 мин','16','Американский хвостик','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('338', '106 мин','11','Американский Шаолинь: Король кикбоксинга II','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('339', '91 мин','11','Американский якудза','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('340', '84 мин','11','Американский якудза 2','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('341', '74 мин','2','Американское безумие','1932');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('342', '101 мин','1','Американское великолепие','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('343', '114 мин','2','Американское сердце','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('344', '84 мин','4','Американское убийство','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('345', '120 мин','2','Американцы','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('346', '116 мин','11','Америкэн бой','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('347', '147 мин','2','Амистад','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('348', '97 мин','17','Амнезия','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('349', '84 мин','4','Амнезия','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('350', '79 мин','1','Амнистия','1981');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('351', '93 мин','2','Аморальное поведение','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('352', '104 мин','14','Аморальные истории','1973');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('353', '90 мин','11','Амстердамское убийство','1977');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('354', '75 мин','2','Амуланга','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('355', '','6','Анаис','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('356', '86 мин','11','Анаконда','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('357', '97 мин','13','Анаконда 2: Охота за Проклятой орхидеей','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('358', '96 мин','1','Анализируй то!','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('359', '103 мин','1','Анализируй это','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('360', '','1','Ананасовый экспресс: сижу, курю','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('361', '89 мин','16','Анастасия','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('362', '104 мин','2','Анастасия','1956');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('363', '200 мин','2','Анастасия: тайна Анны','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('364', '95 мин','4','Анатомия','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('365', '87 мин','3','Анатомия любви','1972');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('366', '98 мин','14','Анатомия порока','2001');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('367', '159 мин','2','Анатомия убийства','1959');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('368', '97 мин','8','Ангар 18','1980');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('369', '134 мин','2','Ангел','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('370', '6 мин','9','Ангел','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('371', '151 мин','2','Ангел за моим столом','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('372', '96 мин','11','Ангел мести','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('373', '520 мин','1','Ангел на дорогах','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('374', '','2','Ангел на обочине','2004');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('375', '88 мин','6','Ангел ночи','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('376', '94 мин','12','Ангел отмщения','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('377', '86 мин','11','Ангел разрушения','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('378', '90 мин','11','Ангел смерти','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('379', '77 мин','11','Ангел ярости','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('380', '88 мин','1','Ангел-А','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('381', '95 мин','2','Ангел-истребитель','1962');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('382', '86 мин','14','Ангелочек','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('383', '99 мин','2','Ангелочек','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('384', '94 мин','11','Ангелочек','1983');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('385', '98 мин','11','Ангелочек 3: Последняя глава','1988');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('386', '94 мин','4','Ангелочек 4: В подполье','1993');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('387', '88 мин','2','Ангелочек, сделай радость','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('388', '91 мин','8','Ангел-хранитель','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('389', '95 мин','11','Ангелы ада на колесах','1967');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('390', '100 мин','2','Ангелы возмездия','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('391', '89 мин','4','Ангелы города','1989');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('392', '90 мин','4','Ангелы здесь не живут','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('393', '','4','Ангелы и демоны','2009');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('394', '118 мин','2','Ангелы и насекомые','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('395', '77 мин','2','Ангелы над Бродвеем','1940');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('396', '95 мин','3','Ангелы с грязными лицами','1938');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('397', '102 мин','2','Ангелы у кромки поля','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('398', '98 мин','11','Ангелы Чарли','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('399', '106 мин','11','Ангелы Чарли: Только вперед','2003');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('400', '81 мин','11','Ангелы черного пояса','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('401', '90 мин','3','Ангельские глазки','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('402', '91 мин','4','Ангельское личико','1953');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('403', '162 мин','2','Английский пациент','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('404', '87 мин','1','Английский цирюльник','2000');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('405', '85 мин','11','Англичанин','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('406', '60 мин','2','Англичанин за границей','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('407', '95 мин','1','Англичанин, который поднялся на холм, а спустился с горы','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('408', '90 мин','1','Ангус','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('409', '33 мин','2','Андалузский пес','1928');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('410', '163 мин','2','Андеграунд','1995');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('411', '','18','Андерсен. Жизнь без любви','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('412', '170 мин','12','Андерсонвилль','1996');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('413', '89 мин','14','Андреа: совсем нагишом, и чем это кончается','1976');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('414', '52 мин','5','Андрей Миронов. Обыкновенное чудо','2006');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('415', '189 мин','2','Андрей Рублев','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('416', '79 мин','8','Андроид','1982');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('417', '96 мин','11','Андрэ','1994');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('418', '72 мин','1','Анекдоты','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('419', '104 мин','11','Анжелика - маркиза ангелов','1964');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('420', '99 мин','11','Анжелика и король','1966');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('421', '104 мин','11','Анжелика и султан','1967');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('422', '130 мин','1','Анискин и Фантомас','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('423', '101 мин','1','Анкор, еще анкор!','1992');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('424', '99 мин','2','Анна','1987');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('425', '100 мин','2','Анна','2005');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('426', '85 мин','3','Анна и командор','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('427', '142 мин','3','Анна и король','1999');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('428', '128 мин','2','Анна и король Сиама','1946');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('429', '123 мин','2','Анна Карамазофф','1991');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('430', '29 мин','2','Анна Каренина','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('431', '145 мин','2','Анна Каренина','1967');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('432', '95 мин','2','Анна Каренина','1935');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('433', '160 мин','2','Анна Каренина','2008');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('434', '80 мин','2','Анна Каренина','1974');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('435', '165 мин','3','Анна Каренина','1953');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('436', '108 мин','2','Анна Каренина','1997');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('437', '88 мин','2','Анна Кристи','1930');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('438', '145 мин','12','Анна на тысячу дней','1969');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('439', '81 мин','2','Анна на шее','1954');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('440', '155 мин','2','Анна Павлова','1983');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('441', '99 мин','8','Аннигилятор','1986');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('442', '87 мин','11','Аннигиляторы','1985');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('443', '89 мин','2','Аннушка','1959');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('444', '55 мин','12','Аноха','1932');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('445', '112 мин','11','Антарктика','1984');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('446', '209 мин','13','Антарктическая повесть','1979');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('447', '56 мин','5','Антарктическое приключение','1990');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('448', '90 мин','11','Антидурь','2007');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('449', '114 мин','11','Антикиллер','2002');
INSERT INTO movies (id, duration,genre,title,year) VALUES ('450', '126 мин','11','Антикиллер 2: Антитеррор','2003');


CREATE TABLE genres (
  title varchar(255) NOT NULL,
  id serial NOT NULL
);


INSERT INTO genres (id, title) VALUES ('1', 'комедия');
INSERT INTO genres (id, title) VALUES ('2', 'драма');
INSERT INTO genres (id, title) VALUES ('3', 'мелодрама');
INSERT INTO genres (id, title) VALUES ('4', 'детектив');
INSERT INTO genres (id, title) VALUES ('5', 'документальный');
INSERT INTO genres (id, title) VALUES ('6', 'ужасы');
INSERT INTO genres (id, title) VALUES ('7', 'музыка');
INSERT INTO genres (id, title) VALUES ('8', 'фантастика');
INSERT INTO genres (id, title) VALUES ('9', 'анимация');
INSERT INTO genres (id, title) VALUES ('10', 'биография');
INSERT INTO genres (id, title) VALUES ('11', 'боевик');
INSERT INTO genres (id, title) VALUES ('12', 'че тут епта');
INSERT INTO genres (id, title) VALUES ('13', 'приключения');
INSERT INTO genres (id, title) VALUES ('14', 'для взрослых');
INSERT INTO genres (id, title) VALUES ('15', 'война');
INSERT INTO genres (id, title) VALUES ('16', 'семейный');
INSERT INTO genres (id, title) VALUES ('17', 'триллер');
INSERT INTO genres (id, title) VALUES ('18', 'фэнтези');
INSERT INTO genres (id, title) VALUES ('19', 'вестерн');
INSERT INTO genres (id, title) VALUES ('20', 'мистика');
INSERT INTO genres (id, title) VALUES ('21', 'короткометражный');
INSERT INTO genres (id, title) VALUES ('22', 'мюзикл');
INSERT INTO genres (id, title) VALUES ('23', 'исторический');
INSERT INTO genres (id, title) VALUES ('24', 'нуар');
